# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/rainbowmaker',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/rainbowmaker',
                'lib_path': 'rainbowmaker'},
  'syms': { 'rainbowmaker.core': {'rainbowmaker.core.foo': ('core.html#foo', 'rainbowmaker/core.py')},
            'rainbowmaker.reader': {'rainbowmaker.reader.read_pda': ('reader.html#read_pda', 'rainbowmaker/reader.py')}}}
